apiVersion: v1
kind: ConfigMap
metadata:
  name: gemini-config
  namespace: gemini-namespace
data:
  GOOGLE_ID: 942482771576-uc3k9ntejl4irji5eriq916r4b6btqjg.apps.googleusercontent.com
  MONGODB_URI: mongodb://mongodb-service:27017/gemini
  NEXTAUTH_URL: https://3.87.50.114.nip.io
  MONGO_INITDB_ROOT_USERNAME: admin
