apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLV9NWVktc2ZPNmZ2VS1yeWdsZ0hnUlVtRVl5NW4= # Base64 for google key
  NEXTAUTH_SECRET: Uy9QOHFMQkUwL0Qram1HVHg0blVndTRkSmRiVTFhMmlZZ2VMa1Q3SVYrYz0= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5RFcyUVFXOGtfdzExemxDdVlnWGxGMmlSUWZwUlZwQnIw # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
