apiVersion: v1
kind: Secret
metadata:
  name: gemini-secret
  namespace: gemini-namespace 
type: Opaque
data:
  GOOGLE_SECRET: R09DU1BYLWJrRE4tS1o0YlFaR0pXSkEtMjNRdDdQWmxQX2U=# Base64 for google key
  NEXTAUTH_SECRET: enZsbm5obVhpc09FTVloalpMT3Y2QlBDSGpNcG5MNklsMkl2eCtjVHBQcz0= # Base64 for auth key
  NEXT_PUBLIC_API_KEY: QUl6YVN5Q3pVeW8wNzNhSkFZSFVsS1AwZUpsRzJWWmVmNmhuNWtn # Base64 for api key
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW5AMTIzCg==  # Base64 for admin@123
